### ISSUE TITLE
Check type of caught error

### ISSUE THREAD

**Issue by mk-pmb** [tunnckoCore/try-read-json#2]
If the error you catch is a SyntaxError, it's probably just some non-JSON input, and you can safely just return false and be done with it. (Even if it's not about bad input, it at least shoudln't be some bad OS problem.) If instead the error was some malfunction that you didn't anticipate, don't assume it's just gonna be fine. Let the invokung program deal with it properly.
I wouldn't even modify the error message in case of an unexpected error, so message-based error handling (although not the best idea) won't need an extra check for your prefix.

**Comment by tunnckoCore** [comment]
Agree. We can just pass the caught error to the callback.

I'm around these modules today, so I will fix that soon. And i'm updating the boilerplate stuff and releasing flow of my libs, so i will come here soon

**Comment by mk-pmb** [comment]
And if there's no callback, throw it.

**Comment by tunnckoCore** [comment]
Yea.

**Comment by mk-pmb** [comment]
Current master still silently drops unknown exceptions if there's no callback.

``` javascript
var trj = require("try-read-json");
JSON.parse = function () {
  throw new Error("Some rare but horrible OS failure!");
};
try {
  console.dir(trj("{}"));  // -> false
} catch (err) {
  console.error('W:', err);
  // not executed. carry on, nothing to worry about, TRJ dealt with it!
}
// Optional: Blame user for supplying malformed JSON
```

**Comment by tunnckoCore** [comment]
Okey, I'm working. I will just remove anything and pass it directly to JSON.parse.

**Comment by tunnckoCore** [comment]
@mk-pmb v2 is out :)

**Comment by mk-pmb** [comment]
Now the error is thrown. Thanks!
