### ISSUE TITLE
Readme should state what subset of JSON is supported

### ISSUE THREAD

**Issue by mk-pmb** [tunnckoCore/try-read-json#3]
Current `index.js` looks like not all JSON data is accepted but only objects and arrays. The readme should clarify that upfront.

**Comment by tunnckoCore** [comment]
hm, right. actually i got an idea

**Comment by tunnckoCore** [comment]
yea, that's crazy... simplified to 4 lines :D

hope https://github.com/hybridables/try-catch-callback/commit/3f5d4fdc96403eee910c3cc1bd0e761890236590 will fix both issues :)

**Comment by mk-pmb** [comment]
Now with v2.x it seems to work for all JSON. Thanks!

**Comment by tunnckoCore** [comment]
Yea, that's great. I don't know why I needed that "strict json" (meaning only array and object) thing.

And actually, try-catch-callback and try-catch-core are freakin awesome packages.
